Da 992/window rename event
PreVeil/fsnotify pull request #1
Opened 2020-01-17 21:46 UTC by parzed

DA-992

For each rename action on a file, two syscall event is generated: 
1- `FILE_ACTION_RENAMED_OLD_NAME`  and
2- `FILE_ACTION_RENAMED_NEW_NAME`.

Here I assumed that the first one is followed by the second one.
Then one fsnorify RENAME event is generated. 
RENAME event has the file's oldName set up. 

the `OldName` attribute is added to the `Event` struct of fsnotify.
The system call of `FILE_ACTION_RENAMED_OLD_NAME` holds the file's old name. Upon receiving this syscall event, `watcher.rename` is set up with the file's old name which serves as a state variable. No fsnotify event is created.

The system call of `FILE_ACTION_RENAMED_NEW_NAME` holds the file's new name. A RENAME fsnotify event is created with file's old name, `watcher.rename`, as `OldName` attribute . 

Cases:
receive  `FILE_ACTION_RENAMED_NEW_NAME` and `watcher.rename` has a value, perfect case, a RENAME event is generated.

receive any syscall rather than `FILE_ACTION_RENAMED_NEW_NAME` and  `watcher.rename`  has a value, first a RENAME event is created with empty name and the OldName is `watcher.rename` value, then the syscall event is handled. 

receive  `FILE_ACTION_RENAMED_NEW_NAME` and `watcher.rename` has no value, a RENAME event is generated with an empty oldName. 

Tests:
in imtegration_test.go

TestFsnotifyMultipleRenames():
generates 1000 rename action and checks if the RENAME attribute is set up correctly and all of the events are received. 

TestFsnotifyRenameEventAttributes():
Checks if the `OldName` attribute is set up correctly for a rename event

2020-01-20 22:54 UTC, hu13 commented
```
receive any syscall rather than FILE_ACTION_RENAMED_NEW_NAME and watcher.rename has a value, first a RENAME event is created with empty name and the OldName is watcher.rename value, then the syscall event is handled.

receive FILE_ACTION_RENAMED_NEW_NAME and watcher.rename has no value, a RENAME event is generated with an empty oldName.
```
In these imperfect cases, how would drive handle it?
how can these cases happen? on what frequency?

2020-01-21 16:23 UTC, parzed commented
> ```
> receive any syscall rather than FILE_ACTION_RENAMED_NEW_NAME and watcher.rename has a value, first a RENAME event is created with empty name and the OldName is watcher.rename value, then the syscall event is handled.
> 
> receive FILE_ACTION_RENAMED_NEW_NAME and watcher.rename has no value, a RENAME event is generated with an empty oldName.
> ```
> 
> 
> In these imperfect cases, how would drive handle it?
>  This is up to the server I think. 
The Mac watcher (the one that has buffer), if it has a rename event of 'old name' or 'new name' and can not find its match in the buffer it creates an event based on the case. it creates a `DELETE event for the old name case` and  `CREATE event for the new name case`. I think differentiating a faulty rename case from actual `CREATE` and `DELETE` is not a bad idea. 
Anyways, in such a cases server can consider these approach or discarding the events. 


> how can these cases happen? on what frequency?
I have not seen any statistics for that and did not encounter the case in the tests. I can do a search to see in what cases it can happen. I considered them in case of system failures.

2020-02-11 00:20 UTC, ianyh requested changes
Just stylistic comments I already had, but holding off on the rest of the review as we discussed.

2020-02-11 00:20 UTC, ianyh commented on fsnotify.go
> +		return fmt.Sprintf("%q: %q: %s", e.Name, e.OldName, e.Op.String())
We could want the old name in more contexts than just rename. Why not make this conditioned on `e.OldName` not being `nil`?

2020-02-11 00:20 UTC, ianyh commented on windows.go
> +	if mask&sysFSMOVEDFROM == sysFSMOVEDFROM {
Why splitting up the conditions for rename?

2020-02-11 00:20 UTC, ianyh commented on windows.go
> +		w.sendEvent(watch.path, watch.mask&sysFSIGNORED, "")
Would it be more idiomatic for go to pass `nil` here instead of an empty string? cc: @hu13

2020-02-11 00:20 UTC, ianyh commented on windows.go
> +				if !setOldName {
Can you rename this variable to avoid the negation? It's a small detail, but as it is right now I'm having a hard time keeping track of what it actually means.

2020-02-21 20:12 UTC, parzed commented on windows.go
> +		w.sendEvent(watch.path, watch.mask&sysFSIGNORED, "")
I can not assign 'nil' to a string type variable.

2020-04-22 20:12 UTC, hu13 requested changes
Some stylist comments.
I still want to discuss the main logic interactively since I don't fully understand some of it.

2020-04-22 20:12 UTC, hu13 commented on fsnotify.go
> +	return fmt.Sprintf("%q: %q %s - %d", e.Name, e.OldName, e.Op.String(), e.ID)
i prefer adding some description in the print like:

`fmt.Sprintf("newpath=%q,  oldpath=%q, op=%s, eventID=%d", e.Name, e.OldName, e.Op.String(), e.ID)`

2020-04-22 20:12 UTC, hu13 commented on fsnotify_test.go
> +/*
Fix test.

2020-04-22 20:12 UTC, hu13 commented on integration_test.go
i think indentation in this file is inconsistent.

2020-04-22 20:12 UTC, hu13 commented on integration_test.go
> +				newName, _ = filepath.Rel(testDir, event.Name)
check err from filepath.Rel too.

2020-04-22 20:12 UTC, hu13 commented on windows.go
> +				{
doesn't need { }
inside case.

2020-04-22 20:12 UTC, hu13 commented on windows.go
> +				{
same, remove outer { }.

2020-06-11 16:11 UTC, ianyh requested changes

2020-06-11 16:11 UTC, ianyh commented on fsnotify_test.go
> +/*
This still needs to be addressed, right?

2020-06-11 16:11 UTC, ianyh commented on windows.go
> +	fmt.Println(" FSNOTIFY | WINDOWS | CREATE EVENT ::: ", e)
Remove.

2020-06-11 16:11 UTC, ianyh commented on windows.go
> +			fmt.Println("Fstnotify | windows | raw action", raw.Action, fullname)
Remove.

2020-06-11 16:11 UTC, ianyh commented on windows.go
> +					fmt.Println("RENAME OLD", fullname)
Remove.

2020-06-11 16:11 UTC, ianyh commented on windows.go
> +					fmt.Println("RENAME NEW", fullname)
Remove.

2020-06-11 16:11 UTC, ianyh commented on windows.go
> +				if !setOldName {
Could you address my comment here?

2020-06-12 18:55 UTC, parzed commented on integration_test.go
not sure if it's still there

2020-06-12 18:55 UTC, parzed commented on windows.go
> +				if !setOldName {
better?

2020-07-01 20:49 UTC, ianyh requested changes

2020-07-01 20:49 UTC, ianyh commented on integration_test.go
It still looks off. It seems to be a mixture of 1 space indents and tab indents.

2020-07-01 20:49 UTC, ianyh commented on windows.go
> +
Remove.

2020-07-01 20:49 UTC, ianyh commented on windows.go
> +				watch.rename = filepath.Join(watch.path, name)
This is just `fullname`.

2020-07-01 20:49 UTC, ianyh commented on windows.go
>  			case syscall.FILE_ACTION_RENAMED_OLD_NAME:
It looks like in this case you don't set `mask`.

2020-07-01 20:49 UTC, ianyh commented on windows.go
>  			case syscall.FILE_ACTION_RENAMED_OLD_NAME:
Oh, I guess this is just relying on the variable initializing by default to 0 so the ands do the right thing.

2020-07-01 20:49 UTC, ianyh commented on windows.go
> +					if watch.rename != "" {
Can you combine this condition with the above?
```go
!isRenameToEvent && watch.rename != ""
```

2020-07-01 20:49 UTC, ianyh commented on windows.go
> +func CreateFsnotifyEvent(name string, mask uint32, oldname string) Event {
Is this used anywhere?

2020-07-01 20:49 UTC, ianyh commented on windows.go
> +								delete(watch.names, name)
Do you need to return in this case? Otherwise we send two events.

2021-07-14 17:54 UTC, merged